[package]
name = "qmassa"
version = "0.2.2"
license = "Apache-2.0"
edition = "2021"

[dependencies]
anyhow = "1.0.91"
clap = { version = "4.5.20", features = ["derive"] }
crossterm = "0.28.1"
env_logger = "0.11.5"
libc = "0.2.161"
log = "0.4.22"
nix = { version = "0.29.0", features = ["ioctl"] }
ratatui = "0.29.0"
serde = { version = "1.0.213", features = ["derive"] }
serde_json = "1.0.132"
tui-widgets = { version = "0.4.0", features = ["scrollview"] }
udev = { version = "0.9.1", features = ["hwdb"] }
