[package]
name = "qmassa"
version = "0.3.0"
description = "Terminal-based tool for displaying GPUs usage stats on Linux."
repository = "https://github.com/ulissesf/qmassa"
readme = "README.md"
license = "Apache-2.0"
keywords = ["gpu", "graphics", "usage", "statistics"]
categories = ["command-line-utilities", "graphics"]
edition = "2021"

[dependencies]
anyhow = "1.0.93"
clap = { version = "4.5.20", features = ["derive"] }
crossterm = "0.28.1"
env_logger = "0.11.5"
itertools = "0.13.0"
libc = "0.2.162"
log = "0.4.22"
nix = { version = "0.29.0", features = ["ioctl"] }
ratatui = "0.29.0"
serde = { version = "1.0.214", features = ["derive"] }
serde_json = "1.0.132"
tui-widgets = { version = "0.4.0", features = ["scrollview"] }
udev = { version = "0.9.1", features = ["hwdb"] }
