[package]
name = "qmassa"
version = "0.2.0"
license = "Apache-2.0"
edition = "2021"

[dependencies]
anyhow = "1.0.87"
clap = { version = "4.5.16", features = ["derive"] }
crossterm = "0.28.1"
env_logger = "0.11.5"
libc = "0.2.158"
log = "0.4.22"
ratatui = "0.28.1"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
tui-widgets = { version = "0.3.0", features = ["scrollview"] }
udev = { version = "0.9.0", features = ["hwdb"] }
